import { ThemeVariables } from "../ThemeVariables";

/**
 * Default light theme - base for all other presets
 */
export const defaultPreset: ThemeVariables = {
   primaryColor: "#1976d2",
   accentColor: "#e0e0e0",
   dangerColor: "#d32f2f",
   textColor: "rgba(0, 0, 0, 0.87)",
   backgroundColor: "white",
   surfaceColor: "white",
   borderColor: "lightgray",
   boxShadow: "0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24)",
   boxShadowElevated:
      "0 2px 8px rgba(0, 0, 0, 0.1), 0 2px 8px rgba(0, 0, 0, 0.15)",
   focusBoxShadow: "0 0 0 2px rgba(25, 118, 210, 0.4)",
   borderRadius: "4px",
   baseFontSize: "14px",
   iconSize: "16px",
   fontFamily: "'Inter', sans-serif",
   fontWeight: "400",
   transition: "all 0.2s ease",

   scrollbarThumbColor: "rgba(128, 128, 128, 0.4)",
   scrollbarTrackColor: "rgba(128, 128, 128, 0.1)",
   scrollbarWidth: "auto",

   primaryTextColor: "white",
   primaryBorderColor:
      "color-mix(in srgb, var(--cx-theme-primary-color), var(--cx-button-active-state-mix-color) 20%)",
   accentTextColor: "rgba(0, 0, 0, 0.87)",
   warningColor: "#f09037",
   warningTextColor: "white",
   warningBorderColor: "transparent",
   successColor: "#5cb85c",
   successTextColor: "white",
   successBorderColor: "transparent",
   dangerTextColor: "white",
   dangerBorderColor:
      "color-mix(in srgb, var(--cx-theme-danger-color), var(--cx-button-active-state-mix-color) 20%)",

   labelPaddingX: "0",
   labelPaddingY: "var(--cx-input-padding-y)",
   labelFontSize: "calc(var(--cx-theme-base-font-size) - 1px)",
   labelFontFamily: "var(--cx-theme-font-family)",
   labelFontWeight: "inherit",
   labelLineHeight: "var(--cx-input-line-height)",
   labelColor: "rgba(0, 0, 0, 0.6)",
   placeholderColor: "rgba(128, 128, 128, 0.7)",

   inputWidth: "200px",
   inputColor: "inherit",
   inputBackgroundColor: "white",
   inputBorderColor: "lightgray",
   inputFontSize: "var(--cx-theme-base-font-size)",
   inputLineHeight: "22px",
   inputPaddingX: "6px",
   inputPaddingY: "6px",
   inputBorderWidth: "1px",
   inputTagBackgroundColor: "var(--cx-button-background-color)",
   inputTagFontSize: "var(--cx-button-font-size)",
   inputTagSpacing: "3px",
   inputTagBorderRadius: "var(--cx-button-border-radius)",
   inputTagBorderWidth: "var(--cx-button-border-width)",
   inputTagPadding:
      "calc(var(--cx-input-padding-y) - var(--cx-input-tag-spacing) - var(--cx-input-tag-border-width))",
   checkboxSize: "16px",

   buttonBackgroundColor: "#f5f5f5",
   buttonColor:
      "oklch(from var(--cx-button-background-color) calc(1 - round(l - 0.15)) 0 0)",
   buttonBorderColor: "var(--cx-theme-border-color)",
   buttonFontSize: "var(--cx-theme-base-font-size)",
   buttonFontWeight: "var(--cx-theme-font-weight)",
   buttonLineHeight: "22px",
   buttonPaddingX: "16px",
   buttonPaddingY: "6px",
   buttonBorderWidth: "1px",
   buttonBoxShadow: "inset 0 -2px rgba(128, 128, 128, 0.1)",
   buttonBorderRadius: "var(--cx-theme-border-radius)",
   buttonHoverBoxShadow:
      "var(--cx-button-box-shadow), 0 0 3px rgba(0, 0, 0, 0.3)",
   buttonHoverStateMixColor: "var(--cx-theme-background-color)",
   buttonHoverStateMixAmount: "8%",
   buttonActiveStateMixColor: "black",
   buttonActiveStateMixAmount: "12%",

   switchAxisSize: "calc(var(--cx-checkbox-size) + 4px)",
   switchHandleSize: "var(--cx-checkbox-size)",
   switchWidth: "calc(var(--cx-checkbox-size) * 2 + 4px)",

   gridBackground: "white",
   gridBorderRadius: "var(--cx-theme-border-radius)",
   gridFontSize: "var(--cx-theme-base-font-size)",
   gridHeaderFontSize: "calc(var(--cx-theme-base-font-size) - 2px)",
   gridHeaderPaddingX: "var(--cx-input-padding-x)",
   gridHeaderPaddingY: "var(--cx-input-padding-y)",
   gridHeaderBackgroundColor: "var(--cx-button-background-color)",
   gridHeaderFontWeight: "600",
   gridDataPaddingX: "var(--cx-input-padding-x)",
   gridDataPaddingY: "var(--cx-input-padding-y)",
   gridDataBackgroundColor: "none",
   gridDataBorderColor: "#e0e0e0",

   listItemPaddingX: "calc(var(--cx-input-padding-y) * 1.5)",
   listItemPaddingY: "var(--cx-input-padding-y)",

   menuItemPaddingX: "var(--cx-button-padding-x)",
   menuItemPaddingY: "var(--cx-button-padding-y)",

   dropdownPadding: "6px",
   dropdownBorderWidth: "1px",
   dropdownArrowSize: "6px",
   dropdownArrowOffset: "24px",
   dropdownArrowShadowColor: "rgba(0, 0, 0, 0.15)",
   dropdownArrowShadowSize: "2px",
   dropdownArrowShadowOffset: "2px",

   toastBackgroundColor: "var(--cx-theme-surface-color)",
   toastBorderWidth: "1px",
   toastBorderColor: "var(--cx-theme-border-color)",
   toastBoxShadow: "var(--cx-theme-box-shadow-elevated)",
   toastBorderRadius: "var(--cx-theme-border-radius)",
   toastPadding: "var(--cx-button-padding-y)",

   windowBackgroundColor: "var(--cx-theme-surface-color)",
   windowBorderColor: "var(--cx-theme-border-color)",
   windowColor: "var(--cx-theme-text-color)",
   windowFontSize: "var(--cx-theme-base-font-size)",
   windowBorderWidth: "1px",
   windowHeaderColor: "var(--cx-theme-primary-color)",
   windowHeaderBackgroundColor: "transparent",
   windowHeaderPadding:
      "var(--cx-button-padding-x) var(--cx-button-padding-x) 0",
   windowHeaderMargin: "0",
   windowHeaderFontSize: "18px",
   windowHeaderFontWeight: "500",
   windowHeaderBorderWidth: "0",
   windowBodyPadding: "var(--cx-button-padding-x)",
   windowBodyBackgroundColor: "transparent",
   windowFooterBackgroundColor: "transparent",
   windowFooterPadding:
      "0 var(--cx-button-padding-x) var(--cx-button-padding-x)",
   windowFooterMargin: "0",
   windowFooterBorderWidth: "0",

   sectionBackgroundColor: "var(--cx-theme-surface-color)",
   sectionBorderColor: "var(--cx-theme-border-color)",
   sectionColor: "var(--cx-theme-text-color)",
   sectionBoxShadow: "none",
   sectionBorderWidth: "1px",
   sectionBorderRadius: "var(--cx-theme-border-radius)",
   sectionHeaderPadding:
      "var(--cx-button-padding-x) var(--cx-button-padding-x) 0",
   sectionHeaderMargin: "0",
   sectionHeaderBorderWidth: "0",
   sectionHeaderFontWeight: "600",
   sectionBodyPadding:
      "var(--cx-button-padding-y) var(--cx-button-padding-x) var(--cx-button-padding-x)",
   sectionFooterPadding:
      "0 var(--cx-button-padding-x) var(--cx-button-padding-x)",
   sectionFooterMargin: "0",
   sectionFooterBorderWidth: "0",

   tooltipBackgroundColor: "white",
   tooltipBorderColor: "var(--cx-theme-border-color)",
   tooltipBorderWidth: "1px",
   tooltipBorderRadius: "var(--cx-theme-border-radius)",
   tooltipArrowSize: "5px",
   tooltipColor: "var(--cx-theme-text-color)",
   tooltipFontSize: "var(--cx-theme-base-font-size)",
   tooltipPadding: "var(--cx-button-padding-y)",
   tooltipBoxShadow: "var(--cx-theme-box-shadow-elevated)",
   tooltipErrorBackgroundColor: "var(--cx-theme-danger-color)",
   tooltipErrorBorderColor: "var(--cx-theme-danger-border-color)",
   tooltipErrorColor: "var(--cx-theme-danger-text-color)",

   sliderAxisColor: "var(--cx-theme-border-color)",
   sliderAxisSize: "6px",
   sliderRangeColor: "var(--cx-theme-primary-color)",
   sliderHandleColor: "var(--cx-theme-primary-color)",
   sliderHandleBorderColor: "var(--cx-slider-handle-color)",
   sliderHandleBorderWidth: "1px",
   sliderHandleSize: "18px",
   sliderHandleBoxShadow: "var(--cx-button-box-shadow)",
   sliderHandleHoverBoxShadow: "var(--cx-button-hover-box-shadow)",

   progressBarHeight: "16px",
   progressBarBackgroundColor: "var(--cx-theme-border-color)",
   progressBarIndicatorColor: "var(--cx-theme-primary-color)",
   progressBarColor: "var(--cx-theme-primary-text-color)",
   progressBarBorderRadius: "var(--cx-theme-border-radius)",

   monthPickerBackgroundColor: "var(--cx-input-background-color)",
   monthPickerBorderWidth: "var(--cx-input-border-width)",
   monthPickerWidth: "20em",
   monthPickerPadding: "var(--cx-input-padding-y)",
   monthPickerCellPadding: "var(--cx-input-padding-y) var(--cx-input-padding-x)",
   monthPickerCellLineHeight: "var(--cx-input-line-height)",
   monthPickerFontSize: "var(--cx-theme-base-font-size)",
   monthPickerCellFontSize: "smaller",
   monthPickerQuarterColor: "var(--cx-theme-primary-color)",
   monthPickerYearFontSize: "inherit",
   monthPickerYearFontWeight: "500",
   monthPickerYearColor: "var(--cx-theme-primary-color)",

   chartAxisLineColor: "rgba(128, 128, 128, 0.2)",
   chartAxisTickColor: "rgba(128, 128, 128, 0.3)",
   chartAxisLabelColor: "currentColor",
   chartAxisLabelFontSize: "smaller",
   chartGridlineColor: "rgba(128, 128, 128, 0.15)",
   chartShapeFillColor: "#eee",
   chartShapeStrokeColor: "#ccc",
   chartShapeStrokeWidth: "1px",
   chartSelectedStrokeWidth: "2px",
   chartLineStrokeColor: "gray",
   chartLineStrokeWidth: "2px",
   chartAreaOpacity: "0.5",
   chartMarkerColor: "rgb(128, 128, 128)",
   chartMarkerStrokeWidth: "1px",
   chartMarkerLineStrokeWidth: "1px",
   chartRangeFillColor: "lightgray",
   chartRangeOpacity: "0.3",
   chartRangeMarkerColor: "#696969",
   chartSwimlaneLaneColor: "#f1f1f1",
   chartLegendFontSize: "smaller",
   chartLegendPadding: "var(--cx-input-padding-y)",
   chartLegendGap: "var(--cx-input-padding-y) var(--cx-input-padding-x)",
   chartLegendEntryGap: "var(--cx-input-padding-y)",
   chartLegendShapeColor: "rgba(128, 128, 128, 0.1)",
   chartLegendShapeStrokeWidth: "1px",

   paletteColor0: "rgba(244, 67, 54, 1)",
   paletteColor1: "rgba(233, 30, 99, 1)",
   paletteColor2: "rgba(156, 39, 176, 1)",
   paletteColor3: "rgba(103, 58, 183, 1)",
   paletteColor4: "rgba(63, 81, 181, 1)",
   paletteColor5: "rgba(33, 150, 243, 1)",
   paletteColor6: "rgba(3, 169, 244, 1)",
   paletteColor7: "rgba(0, 188, 212, 1)",
   paletteColor8: "rgba(0, 150, 136, 1)",
   paletteColor9: "rgba(76, 175, 80, 1)",
   paletteColor10: "rgba(139, 195, 74, 1)",
   paletteColor11: "rgba(205, 220, 57, 1)",
   paletteColor12: "rgba(255, 235, 59, 1)",
   paletteColor13: "rgba(255, 193, 7, 1)",
   paletteColor14: "rgba(255, 152, 0, 1)",
   paletteColor15: "rgba(255, 87, 34, 1)",
   paletteFillWhiten: "30%",
   paletteFillHoverWhiten: "50%",
   paletteFillSelectedWhiten: "0%",
   paletteFillDisabledWhiten: "90%",
   paletteFillBlacken: "5%",
   paletteFillHoverBlacken: "5%",
   paletteFillSelectedBlacken: "7%",
   paletteFillDisabledBlacken: "0%",
   paletteStrokeWhiten: "0%",
   paletteStrokeBlacken: "10%",

   colorPickerBorderWidth: "var(--cx-input-border-width)",

   calendarBorderWidth: "var(--cx-input-border-width)",
   calendarBackgroundColor: "white",
   calendarPadding: "var(--cx-input-padding-y)",
   calendarHeaderFontWeight: "500",
   calendarHeaderBackgroundColor: "transparent",
   calendarDayPaddingX: "calc(1.5 * var(--cx-input-padding-y))",
   calendarDayPaddingY: "var(--cx-input-padding-y)",
   calendarDayLineHeight: "var(--cx-input-line-height)",
   calendarDayFontSize: "var(--cx-theme-base-font-size)",
};
